#!/bin/bash
# Guardrail: keep the pkgdown reference index in sync with the package's
# exported topics. A new export (added to NAMESPACE by devtools::document())
# that is not listed in _pkgdown.yml makes `pkgdown::build_site()` fail in CI
# with "N topic(s) missing from index". This hook runs pkgdown::check_pkgdown()
# right after the two events that can make the index stale, and blocks (exit 2)
# so the mistake is fixed before moving on.
#
# Triggers (decided in tool_name / tool_input on stdin):
#   - devtools::document() ran         (Bash command containing "document(",
#                                        or the r-btw MCP document tool)
#   - _pkgdown.yml was edited/written  (Edit/Write/MultiEdit of _pkgdown.yml)
#
# NAMESPACE is intentionally NOT a trigger: it is never hand-edited (it is
# regenerated by document()), so document() is the real signal.
#
# No-op unless a _pkgdown.yml exists at/above the working directory, so this
# is silent in non-pkgdown packages and non-R projects.
#
# Wired up via a PostToolUse hook in this plugin's hooks/hooks.json.

INPUT=$(cat)

TOOL=$(printf '%s' "$INPUT" | jq -r '.tool_name // empty' 2>/dev/null)
CMD=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)
FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)
CWD=$(printf '%s' "$INPUT" | jq -r '.cwd // empty' 2>/dev/null)
CWD=${CWD:-$PWD}

# Decide whether this tool call is a trigger.
trigger=0
case "$TOOL" in
  Bash)
    # devtools::document() / roxygen2::roxygenise() run from a shell.
    case "$CMD" in
      *document\(* | *roxygenise\(* | *roxygenize\(*) trigger=1 ;;
    esac
    ;;
  mcp__r-btw__btw_tool_pkg_document)
    trigger=1
    ;;
  Edit | Write | MultiEdit)
    [ "$(basename "$FILE")" = "_pkgdown.yml" ] && trigger=1
    ;;
esac

[ "$trigger" -eq 1 ] || exit 0

# Find the package root: the nearest directory at/above CWD holding a
# _pkgdown.yml. No _pkgdown.yml anywhere -> nothing to check, no-op.
dir=$CWD
pkg_root=""
while [ -n "$dir" ] && [ "$dir" != "/" ]; do
  if [ -f "$dir/_pkgdown.yml" ] || [ -f "$dir/pkgdown/_pkgdown.yml" ]; then
    pkg_root=$dir
    break
  fi
  dir=$(dirname "$dir")
done
[ -n "$pkg_root" ] || exit 0

# A pkgdown site needs a DESCRIPTION alongside the config; bail quietly if the
# _pkgdown.yml is not actually at an R package root.
[ -f "$pkg_root/DESCRIPTION" ] || exit 0

command -v Rscript >/dev/null 2>&1 || exit 0

# Run the check. check_pkgdown() errors (non-zero) when a topic is missing from
# or dangling in the index; it prints "No problems found." and exits 0 when the
# index is in sync. Capture output so we can hand the actual message back.
OUTPUT=$(cd "$pkg_root" && NOT_CRAN=true Rscript -e 'pkgdown::check_pkgdown(".")' 2>&1)
STATUS=$?

if [ "$STATUS" -ne 0 ]; then
  {
    echo "pkgdown reference index is out of sync (pkgdown::check_pkgdown() failed):"
    echo
    printf '%s\n' "$OUTPUT"
    echo
    echo "Fix _pkgdown.yml: add the missing topic(s) to the reference index"
    echo "(or mark the function @keywords internal to drop it from the index),"
    echo "then re-run devtools::document()."
  } >&2
  exit 2
fi

exit 0
